version: 2


jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image:  shuhein-docker-local.jfrog.io/cobolcnvert:0.1 # the primary container, where your job's commands are run
        auth:
          username: admin
          password: Tb0Gx1Sp1Wd6Xn
    working_directory: ~/hogehoge
    steps:
      - checkout
      - run: cp /home/tools/cobolconv/build.gradle .
      - run: gradle COBOLconvert
      - run: gradle upload

