version: 2


jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: shuhein-docker-local.jfrog.io/circlecibase:0.2 # the primary container, where your job's commands are run
      auth:
        username: admin
        password: Tb0Gx1Sp1Wd6Xn
    working_directory: ~/hogehoge
    environment:
      TAEGET_DIR: _converted
    steps:
      - checkout
      - run: cp /home/tools/cobolconv/build.gradle .
      - run:
          command: |
            mkdir  -p $TAEGET_DIR       
            echo 'export archiveFile=$(git show -s --format=%H).tar.gz' >> $BASH_ENV
            source $BASH_ENV
            touch $TAEGET_DIR/$archiveFile
            ls $TAEGET_DIR
      # - run: gradle COBOLconvert
      # - run: 
      #     command: |
      #       mkdir -p $TAEGET_DIR
      #       tar czf $archivePath convertedCodes
      - store_artifacts:
          path: $TAEGET_DIR
          destination: converted
      # - run: gradle upload



