version: 2


jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
    - image: shuhein-docker-local.jfrog.io/circlecibase:0.2 # the primary container, where your job's commands are run
      auth:
        username: admin
        password: Tb0Gx1Sp1Wd6Xn
    working_directory: ~/hogehoge
    steps:
      - checkout
      - run: cp /home/tools/cobolconv/build.gradle .
      - run:
          command: |
            echo 'export archiveFile=$(git show -s --format=%H).tar.gz' >> $BASH_ENV
            source $BASH_ENV
            touch /tmp/result/$archiveFile
      - run: gradle COBOLconvert
      - run: 
          command: |
            mkdir -p /tmp/result
            tar czf /tmp/result/$archiveFile convertedCodes
      - store_artifacts:  #$refができない・・・ので直書き
          path: /tmp/conv
          destination: converted
      # - run: gradle upload



